name: "🐞 Bug report"
description: Report a problem you encountered with PromptConfigs
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below so we can investigate.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the bug
      placeholder: "e.g. One-click copy button does nothing in Cursor"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide numbered steps so we can reproduce the issue
      placeholder: |
        1. Go to …
        2. Click on …
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What you thought would happen"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "What actually happened"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Include any details (browser, OS, IDE/tool version)
      placeholder: "Chrome 119 on macOS, Cursor v0.38"
